/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as InitiativesRouteImport } from './routes/initiatives'
import { Route as Ikf360RouteImport } from './routes/ikf360'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CodepenExportRouteImport } from './routes/codepen-export'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Ikf360IndexRouteImport } from './routes/ikf360.index'
import { Route as Ikf360UploadRouteImport } from './routes/ikf360.upload'
import { Route as Ikf360IntentRouteImport } from './routes/ikf360.intent'
import { Route as Ikf360DashboardRouteImport } from './routes/ikf360.dashboard'
import { Route as Ikf360AdminRouteImport } from './routes/ikf360.admin'
import { Route as Ikf360AdminIdRouteImport } from './routes/ikf360.admin.$id'

const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesRoute = InitiativesRouteImport.update({
  id: '/initiatives',
  path: '/initiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const Ikf360Route = Ikf360RouteImport.update({
  id: '/ikf360',
  path: '/ikf360',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CodepenExportRoute = CodepenExportRouteImport.update({
  id: '/codepen-export',
  path: '/codepen-export',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Ikf360IndexRoute = Ikf360IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Ikf360Route,
} as any)
const Ikf360UploadRoute = Ikf360UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => Ikf360Route,
} as any)
const Ikf360IntentRoute = Ikf360IntentRouteImport.update({
  id: '/intent',
  path: '/intent',
  getParentRoute: () => Ikf360Route,
} as any)
const Ikf360DashboardRoute = Ikf360DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => Ikf360Route,
} as any)
const Ikf360AdminRoute = Ikf360AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => Ikf360Route,
} as any)
const Ikf360AdminIdRoute = Ikf360AdminIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => Ikf360AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coaches': typeof CoachesRoute
  '/codepen-export': typeof CodepenExportRoute
  '/donate': typeof DonateRoute
  '/ikf360': typeof Ikf360RouteWithChildren
  '/initiatives': typeof InitiativesRoute
  '/parents': typeof ParentsRoute
  '/partners': typeof PartnersRoute
  '/players': typeof PlayersRoute
  '/ikf360/admin': typeof Ikf360AdminRouteWithChildren
  '/ikf360/dashboard': typeof Ikf360DashboardRoute
  '/ikf360/intent': typeof Ikf360IntentRoute
  '/ikf360/upload': typeof Ikf360UploadRoute
  '/ikf360/': typeof Ikf360IndexRoute
  '/ikf360/admin/$id': typeof Ikf360AdminIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coaches': typeof CoachesRoute
  '/codepen-export': typeof CodepenExportRoute
  '/donate': typeof DonateRoute
  '/initiatives': typeof InitiativesRoute
  '/parents': typeof ParentsRoute
  '/partners': typeof PartnersRoute
  '/players': typeof PlayersRoute
  '/ikf360/admin': typeof Ikf360AdminRouteWithChildren
  '/ikf360/dashboard': typeof Ikf360DashboardRoute
  '/ikf360/intent': typeof Ikf360IntentRoute
  '/ikf360/upload': typeof Ikf360UploadRoute
  '/ikf360': typeof Ikf360IndexRoute
  '/ikf360/admin/$id': typeof Ikf360AdminIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coaches': typeof CoachesRoute
  '/codepen-export': typeof CodepenExportRoute
  '/donate': typeof DonateRoute
  '/ikf360': typeof Ikf360RouteWithChildren
  '/initiatives': typeof InitiativesRoute
  '/parents': typeof ParentsRoute
  '/partners': typeof PartnersRoute
  '/players': typeof PlayersRoute
  '/ikf360/admin': typeof Ikf360AdminRouteWithChildren
  '/ikf360/dashboard': typeof Ikf360DashboardRoute
  '/ikf360/intent': typeof Ikf360IntentRoute
  '/ikf360/upload': typeof Ikf360UploadRoute
  '/ikf360/': typeof Ikf360IndexRoute
  '/ikf360/admin/$id': typeof Ikf360AdminIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coaches'
    | '/codepen-export'
    | '/donate'
    | '/ikf360'
    | '/initiatives'
    | '/parents'
    | '/partners'
    | '/players'
    | '/ikf360/admin'
    | '/ikf360/dashboard'
    | '/ikf360/intent'
    | '/ikf360/upload'
    | '/ikf360/'
    | '/ikf360/admin/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coaches'
    | '/codepen-export'
    | '/donate'
    | '/initiatives'
    | '/parents'
    | '/partners'
    | '/players'
    | '/ikf360/admin'
    | '/ikf360/dashboard'
    | '/ikf360/intent'
    | '/ikf360/upload'
    | '/ikf360'
    | '/ikf360/admin/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coaches'
    | '/codepen-export'
    | '/donate'
    | '/ikf360'
    | '/initiatives'
    | '/parents'
    | '/partners'
    | '/players'
    | '/ikf360/admin'
    | '/ikf360/dashboard'
    | '/ikf360/intent'
    | '/ikf360/upload'
    | '/ikf360/'
    | '/ikf360/admin/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoachesRoute: typeof CoachesRoute
  CodepenExportRoute: typeof CodepenExportRoute
  DonateRoute: typeof DonateRoute
  Ikf360Route: typeof Ikf360RouteWithChildren
  InitiativesRoute: typeof InitiativesRoute
  ParentsRoute: typeof ParentsRoute
  PartnersRoute: typeof PartnersRoute
  PlayersRoute: typeof PlayersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives': {
      id: '/initiatives'
      path: '/initiatives'
      fullPath: '/initiatives'
      preLoaderRoute: typeof InitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ikf360': {
      id: '/ikf360'
      path: '/ikf360'
      fullPath: '/ikf360'
      preLoaderRoute: typeof Ikf360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codepen-export': {
      id: '/codepen-export'
      path: '/codepen-export'
      fullPath: '/codepen-export'
      preLoaderRoute: typeof CodepenExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ikf360/': {
      id: '/ikf360/'
      path: '/'
      fullPath: '/ikf360/'
      preLoaderRoute: typeof Ikf360IndexRouteImport
      parentRoute: typeof Ikf360Route
    }
    '/ikf360/upload': {
      id: '/ikf360/upload'
      path: '/upload'
      fullPath: '/ikf360/upload'
      preLoaderRoute: typeof Ikf360UploadRouteImport
      parentRoute: typeof Ikf360Route
    }
    '/ikf360/intent': {
      id: '/ikf360/intent'
      path: '/intent'
      fullPath: '/ikf360/intent'
      preLoaderRoute: typeof Ikf360IntentRouteImport
      parentRoute: typeof Ikf360Route
    }
    '/ikf360/dashboard': {
      id: '/ikf360/dashboard'
      path: '/dashboard'
      fullPath: '/ikf360/dashboard'
      preLoaderRoute: typeof Ikf360DashboardRouteImport
      parentRoute: typeof Ikf360Route
    }
    '/ikf360/admin': {
      id: '/ikf360/admin'
      path: '/admin'
      fullPath: '/ikf360/admin'
      preLoaderRoute: typeof Ikf360AdminRouteImport
      parentRoute: typeof Ikf360Route
    }
    '/ikf360/admin/$id': {
      id: '/ikf360/admin/$id'
      path: '/$id'
      fullPath: '/ikf360/admin/$id'
      preLoaderRoute: typeof Ikf360AdminIdRouteImport
      parentRoute: typeof Ikf360AdminRoute
    }
  }
}

interface Ikf360AdminRouteChildren {
  Ikf360AdminIdRoute: typeof Ikf360AdminIdRoute
}

const Ikf360AdminRouteChildren: Ikf360AdminRouteChildren = {
  Ikf360AdminIdRoute: Ikf360AdminIdRoute,
}

const Ikf360AdminRouteWithChildren = Ikf360AdminRoute._addFileChildren(
  Ikf360AdminRouteChildren,
)

interface Ikf360RouteChildren {
  Ikf360AdminRoute: typeof Ikf360AdminRouteWithChildren
  Ikf360DashboardRoute: typeof Ikf360DashboardRoute
  Ikf360IntentRoute: typeof Ikf360IntentRoute
  Ikf360UploadRoute: typeof Ikf360UploadRoute
  Ikf360IndexRoute: typeof Ikf360IndexRoute
}

const Ikf360RouteChildren: Ikf360RouteChildren = {
  Ikf360AdminRoute: Ikf360AdminRouteWithChildren,
  Ikf360DashboardRoute: Ikf360DashboardRoute,
  Ikf360IntentRoute: Ikf360IntentRoute,
  Ikf360UploadRoute: Ikf360UploadRoute,
  Ikf360IndexRoute: Ikf360IndexRoute,
}

const Ikf360RouteWithChildren =
  Ikf360Route._addFileChildren(Ikf360RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoachesRoute: CoachesRoute,
  CodepenExportRoute: CodepenExportRoute,
  DonateRoute: DonateRoute,
  Ikf360Route: Ikf360RouteWithChildren,
  InitiativesRoute: InitiativesRoute,
  ParentsRoute: ParentsRoute,
  PartnersRoute: PartnersRoute,
  PlayersRoute: PlayersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
