/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InitiativesRouteImport } from './routes/initiatives'
import { Route as Ikf360RouteImport } from './routes/ikf360'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CodepenExportRouteImport } from './routes/codepen-export'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Ikf360IndexRouteImport } from './routes/ikf360.index'
import { Route as ParentsPathwayRouteImport } from './routes/parents_.pathway'
import { Route as Ikf360UploadRouteImport } from './routes/ikf360.upload'
import { Route as Ikf360SupportRouteImport } from './routes/ikf360.support'
import { Route as Ikf360PreReviewRouteImport } from './routes/ikf360.pre-review'
import { Route as Ikf360IntentRouteImport } from './routes/ikf360.intent'
import { Route as Ikf360DashboardRouteImport } from './routes/ikf360.dashboard'
import { Route as Ikf360AdminRouteImport } from './routes/ikf360.admin'
import { Route as Ikf360AdminTemplatesRouteImport } from './routes/ikf360.admin.templates'
import { Route as Ikf360AdminProvidersRouteImport } from './routes/ikf360.admin.providers'
import { Route as Ikf360AdminContentRouteImport } from './routes/ikf360.admin.content'
import { Route as Ikf360AdminCellsRouteImport } from './routes/ikf360.admin.cells'
import { Route as Ikf360AdminAxesRouteImport } from './routes/ikf360.admin.axes'
import { Route as Ikf360AdminIdRouteImport } from './routes/ikf360.admin.$id'
import { Route as ApiUploadsIdRouteImport } from './routes/api.uploads.$id'
import { Route as ApiCronStage2NudgeRouteImport } from './routes/api.cron.stage2-nudge'
import { Route as ApiCronReviewRemindersRouteImport } from './routes/api.cron.review-reminders'
import { Route as ApiCronMonthlyContentRouteImport } from './routes/api.cron.monthly-content'
import { Route as Ikf360AdminProfilesIdRouteImport } from './routes/ikf360.admin.profiles.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesRoute = InitiativesRouteImport.update({
  id: '/initiatives',
  path: '/initiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const Ikf360Route = Ikf360RouteImport.update({
  id: '/ikf360',
  path: '/ikf360',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CodepenExportRoute = CodepenExportRouteImport.update({
  id: '/codepen-export',
  path: '/codepen-export',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Ikf360IndexRoute = Ikf360IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Ikf360Route,
} as any)
const ParentsPathwayRoute = ParentsPathwayRouteImport.update({
  id: '/parents_/pathway',
  path: '/parents/pathway',
  getParentRoute: () => rootRouteImport,
} as any)
const Ikf360UploadRoute = Ikf360UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => Ikf360Route,
} as any)
const Ikf360SupportRoute = Ikf360SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => Ikf360Route,
} as any)
const Ikf360PreReviewRoute = Ikf360PreReviewRouteImport.update({
  id: '/pre-review',
  path: '/pre-review',
  getParentRoute: () => Ikf360Route,
} as any)
const Ikf360IntentRoute = Ikf360IntentRouteImport.update({
  id: '/intent',
  path: '/intent',
  getParentRoute: () => Ikf360Route,
} as any)
const Ikf360DashboardRoute = Ikf360DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => Ikf360Route,
} as any)
const Ikf360AdminRoute = Ikf360AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => Ikf360Route,
} as any)
const Ikf360AdminTemplatesRoute = Ikf360AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => Ikf360AdminRoute,
} as any)
const Ikf360AdminProvidersRoute = Ikf360AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => Ikf360AdminRoute,
} as any)
const Ikf360AdminContentRoute = Ikf360AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => Ikf360AdminRoute,
} as any)
const Ikf360AdminCellsRoute = Ikf360AdminCellsRouteImport.update({
  id: '/cells',
  path: '/cells',
  getParentRoute: () => Ikf360AdminRoute,
} as any)
const Ikf360AdminAxesRoute = Ikf360AdminAxesRouteImport.update({
  id: '/axes',
  path: '/axes',
  getParentRoute: () => Ikf360AdminRoute,
} as any)
const Ikf360AdminIdRoute = Ikf360AdminIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => Ikf360AdminRoute,
} as any)
const ApiUploadsIdRoute = ApiUploadsIdRouteImport.update({
  id: '/api/uploads/$id',
  path: '/api/uploads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronStage2NudgeRoute = ApiCronStage2NudgeRouteImport.update({
  id: '/api/cron/stage2-nudge',
  path: '/api/cron/stage2-nudge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronReviewRemindersRoute = ApiCronReviewRemindersRouteImport.update({
  id: '/api/cron/review-reminders',
  path: '/api/cron/review-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronMonthlyContentRoute = ApiCronMonthlyContentRouteImport.update({
  id: '/api/cron/monthly-content',
  path: '/api/cron/monthly-content',
  getParentRoute: () => rootRouteImport,
} as any)
const Ikf360AdminProfilesIdRoute = Ikf360AdminProfilesIdRouteImport.update({
  id: '/profiles/$id',
  path: '/profiles/$id',
  getParentRoute: () => Ikf360AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coaches': typeof CoachesRoute
  '/codepen-export': typeof CodepenExportRoute
  '/donate': typeof DonateRoute
  '/ikf360': typeof Ikf360RouteWithChildren
  '/initiatives': typeof InitiativesRoute
  '/login': typeof LoginRoute
  '/parents': typeof ParentsRoute
  '/partners': typeof PartnersRoute
  '/players': typeof PlayersRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/ikf360/admin': typeof Ikf360AdminRouteWithChildren
  '/ikf360/dashboard': typeof Ikf360DashboardRoute
  '/ikf360/intent': typeof Ikf360IntentRoute
  '/ikf360/pre-review': typeof Ikf360PreReviewRoute
  '/ikf360/support': typeof Ikf360SupportRoute
  '/ikf360/upload': typeof Ikf360UploadRoute
  '/parents/pathway': typeof ParentsPathwayRoute
  '/ikf360/': typeof Ikf360IndexRoute
  '/api/cron/monthly-content': typeof ApiCronMonthlyContentRoute
  '/api/cron/review-reminders': typeof ApiCronReviewRemindersRoute
  '/api/cron/stage2-nudge': typeof ApiCronStage2NudgeRoute
  '/api/uploads/$id': typeof ApiUploadsIdRoute
  '/ikf360/admin/$id': typeof Ikf360AdminIdRoute
  '/ikf360/admin/axes': typeof Ikf360AdminAxesRoute
  '/ikf360/admin/cells': typeof Ikf360AdminCellsRoute
  '/ikf360/admin/content': typeof Ikf360AdminContentRoute
  '/ikf360/admin/providers': typeof Ikf360AdminProvidersRoute
  '/ikf360/admin/templates': typeof Ikf360AdminTemplatesRoute
  '/ikf360/admin/profiles/$id': typeof Ikf360AdminProfilesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coaches': typeof CoachesRoute
  '/codepen-export': typeof CodepenExportRoute
  '/donate': typeof DonateRoute
  '/initiatives': typeof InitiativesRoute
  '/login': typeof LoginRoute
  '/parents': typeof ParentsRoute
  '/partners': typeof PartnersRoute
  '/players': typeof PlayersRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/ikf360/admin': typeof Ikf360AdminRouteWithChildren
  '/ikf360/dashboard': typeof Ikf360DashboardRoute
  '/ikf360/intent': typeof Ikf360IntentRoute
  '/ikf360/pre-review': typeof Ikf360PreReviewRoute
  '/ikf360/support': typeof Ikf360SupportRoute
  '/ikf360/upload': typeof Ikf360UploadRoute
  '/parents/pathway': typeof ParentsPathwayRoute
  '/ikf360': typeof Ikf360IndexRoute
  '/api/cron/monthly-content': typeof ApiCronMonthlyContentRoute
  '/api/cron/review-reminders': typeof ApiCronReviewRemindersRoute
  '/api/cron/stage2-nudge': typeof ApiCronStage2NudgeRoute
  '/api/uploads/$id': typeof ApiUploadsIdRoute
  '/ikf360/admin/$id': typeof Ikf360AdminIdRoute
  '/ikf360/admin/axes': typeof Ikf360AdminAxesRoute
  '/ikf360/admin/cells': typeof Ikf360AdminCellsRoute
  '/ikf360/admin/content': typeof Ikf360AdminContentRoute
  '/ikf360/admin/providers': typeof Ikf360AdminProvidersRoute
  '/ikf360/admin/templates': typeof Ikf360AdminTemplatesRoute
  '/ikf360/admin/profiles/$id': typeof Ikf360AdminProfilesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coaches': typeof CoachesRoute
  '/codepen-export': typeof CodepenExportRoute
  '/donate': typeof DonateRoute
  '/ikf360': typeof Ikf360RouteWithChildren
  '/initiatives': typeof InitiativesRoute
  '/login': typeof LoginRoute
  '/parents': typeof ParentsRoute
  '/partners': typeof PartnersRoute
  '/players': typeof PlayersRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/ikf360/admin': typeof Ikf360AdminRouteWithChildren
  '/ikf360/dashboard': typeof Ikf360DashboardRoute
  '/ikf360/intent': typeof Ikf360IntentRoute
  '/ikf360/pre-review': typeof Ikf360PreReviewRoute
  '/ikf360/support': typeof Ikf360SupportRoute
  '/ikf360/upload': typeof Ikf360UploadRoute
  '/parents_/pathway': typeof ParentsPathwayRoute
  '/ikf360/': typeof Ikf360IndexRoute
  '/api/cron/monthly-content': typeof ApiCronMonthlyContentRoute
  '/api/cron/review-reminders': typeof ApiCronReviewRemindersRoute
  '/api/cron/stage2-nudge': typeof ApiCronStage2NudgeRoute
  '/api/uploads/$id': typeof ApiUploadsIdRoute
  '/ikf360/admin/$id': typeof Ikf360AdminIdRoute
  '/ikf360/admin/axes': typeof Ikf360AdminAxesRoute
  '/ikf360/admin/cells': typeof Ikf360AdminCellsRoute
  '/ikf360/admin/content': typeof Ikf360AdminContentRoute
  '/ikf360/admin/providers': typeof Ikf360AdminProvidersRoute
  '/ikf360/admin/templates': typeof Ikf360AdminTemplatesRoute
  '/ikf360/admin/profiles/$id': typeof Ikf360AdminProfilesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coaches'
    | '/codepen-export'
    | '/donate'
    | '/ikf360'
    | '/initiatives'
    | '/login'
    | '/parents'
    | '/partners'
    | '/players'
    | '/privacy'
    | '/signup'
    | '/ikf360/admin'
    | '/ikf360/dashboard'
    | '/ikf360/intent'
    | '/ikf360/pre-review'
    | '/ikf360/support'
    | '/ikf360/upload'
    | '/parents/pathway'
    | '/ikf360/'
    | '/api/cron/monthly-content'
    | '/api/cron/review-reminders'
    | '/api/cron/stage2-nudge'
    | '/api/uploads/$id'
    | '/ikf360/admin/$id'
    | '/ikf360/admin/axes'
    | '/ikf360/admin/cells'
    | '/ikf360/admin/content'
    | '/ikf360/admin/providers'
    | '/ikf360/admin/templates'
    | '/ikf360/admin/profiles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coaches'
    | '/codepen-export'
    | '/donate'
    | '/initiatives'
    | '/login'
    | '/parents'
    | '/partners'
    | '/players'
    | '/privacy'
    | '/signup'
    | '/ikf360/admin'
    | '/ikf360/dashboard'
    | '/ikf360/intent'
    | '/ikf360/pre-review'
    | '/ikf360/support'
    | '/ikf360/upload'
    | '/parents/pathway'
    | '/ikf360'
    | '/api/cron/monthly-content'
    | '/api/cron/review-reminders'
    | '/api/cron/stage2-nudge'
    | '/api/uploads/$id'
    | '/ikf360/admin/$id'
    | '/ikf360/admin/axes'
    | '/ikf360/admin/cells'
    | '/ikf360/admin/content'
    | '/ikf360/admin/providers'
    | '/ikf360/admin/templates'
    | '/ikf360/admin/profiles/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coaches'
    | '/codepen-export'
    | '/donate'
    | '/ikf360'
    | '/initiatives'
    | '/login'
    | '/parents'
    | '/partners'
    | '/players'
    | '/privacy'
    | '/signup'
    | '/ikf360/admin'
    | '/ikf360/dashboard'
    | '/ikf360/intent'
    | '/ikf360/pre-review'
    | '/ikf360/support'
    | '/ikf360/upload'
    | '/parents_/pathway'
    | '/ikf360/'
    | '/api/cron/monthly-content'
    | '/api/cron/review-reminders'
    | '/api/cron/stage2-nudge'
    | '/api/uploads/$id'
    | '/ikf360/admin/$id'
    | '/ikf360/admin/axes'
    | '/ikf360/admin/cells'
    | '/ikf360/admin/content'
    | '/ikf360/admin/providers'
    | '/ikf360/admin/templates'
    | '/ikf360/admin/profiles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoachesRoute: typeof CoachesRoute
  CodepenExportRoute: typeof CodepenExportRoute
  DonateRoute: typeof DonateRoute
  Ikf360Route: typeof Ikf360RouteWithChildren
  InitiativesRoute: typeof InitiativesRoute
  LoginRoute: typeof LoginRoute
  ParentsRoute: typeof ParentsRoute
  PartnersRoute: typeof PartnersRoute
  PlayersRoute: typeof PlayersRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  ParentsPathwayRoute: typeof ParentsPathwayRoute
  ApiCronMonthlyContentRoute: typeof ApiCronMonthlyContentRoute
  ApiCronReviewRemindersRoute: typeof ApiCronReviewRemindersRoute
  ApiCronStage2NudgeRoute: typeof ApiCronStage2NudgeRoute
  ApiUploadsIdRoute: typeof ApiUploadsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives': {
      id: '/initiatives'
      path: '/initiatives'
      fullPath: '/initiatives'
      preLoaderRoute: typeof InitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ikf360': {
      id: '/ikf360'
      path: '/ikf360'
      fullPath: '/ikf360'
      preLoaderRoute: typeof Ikf360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codepen-export': {
      id: '/codepen-export'
      path: '/codepen-export'
      fullPath: '/codepen-export'
      preLoaderRoute: typeof CodepenExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ikf360/': {
      id: '/ikf360/'
      path: '/'
      fullPath: '/ikf360/'
      preLoaderRoute: typeof Ikf360IndexRouteImport
      parentRoute: typeof Ikf360Route
    }
    '/parents_/pathway': {
      id: '/parents_/pathway'
      path: '/parents/pathway'
      fullPath: '/parents/pathway'
      preLoaderRoute: typeof ParentsPathwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ikf360/upload': {
      id: '/ikf360/upload'
      path: '/upload'
      fullPath: '/ikf360/upload'
      preLoaderRoute: typeof Ikf360UploadRouteImport
      parentRoute: typeof Ikf360Route
    }
    '/ikf360/support': {
      id: '/ikf360/support'
      path: '/support'
      fullPath: '/ikf360/support'
      preLoaderRoute: typeof Ikf360SupportRouteImport
      parentRoute: typeof Ikf360Route
    }
    '/ikf360/pre-review': {
      id: '/ikf360/pre-review'
      path: '/pre-review'
      fullPath: '/ikf360/pre-review'
      preLoaderRoute: typeof Ikf360PreReviewRouteImport
      parentRoute: typeof Ikf360Route
    }
    '/ikf360/intent': {
      id: '/ikf360/intent'
      path: '/intent'
      fullPath: '/ikf360/intent'
      preLoaderRoute: typeof Ikf360IntentRouteImport
      parentRoute: typeof Ikf360Route
    }
    '/ikf360/dashboard': {
      id: '/ikf360/dashboard'
      path: '/dashboard'
      fullPath: '/ikf360/dashboard'
      preLoaderRoute: typeof Ikf360DashboardRouteImport
      parentRoute: typeof Ikf360Route
    }
    '/ikf360/admin': {
      id: '/ikf360/admin'
      path: '/admin'
      fullPath: '/ikf360/admin'
      preLoaderRoute: typeof Ikf360AdminRouteImport
      parentRoute: typeof Ikf360Route
    }
    '/ikf360/admin/templates': {
      id: '/ikf360/admin/templates'
      path: '/templates'
      fullPath: '/ikf360/admin/templates'
      preLoaderRoute: typeof Ikf360AdminTemplatesRouteImport
      parentRoute: typeof Ikf360AdminRoute
    }
    '/ikf360/admin/providers': {
      id: '/ikf360/admin/providers'
      path: '/providers'
      fullPath: '/ikf360/admin/providers'
      preLoaderRoute: typeof Ikf360AdminProvidersRouteImport
      parentRoute: typeof Ikf360AdminRoute
    }
    '/ikf360/admin/content': {
      id: '/ikf360/admin/content'
      path: '/content'
      fullPath: '/ikf360/admin/content'
      preLoaderRoute: typeof Ikf360AdminContentRouteImport
      parentRoute: typeof Ikf360AdminRoute
    }
    '/ikf360/admin/cells': {
      id: '/ikf360/admin/cells'
      path: '/cells'
      fullPath: '/ikf360/admin/cells'
      preLoaderRoute: typeof Ikf360AdminCellsRouteImport
      parentRoute: typeof Ikf360AdminRoute
    }
    '/ikf360/admin/axes': {
      id: '/ikf360/admin/axes'
      path: '/axes'
      fullPath: '/ikf360/admin/axes'
      preLoaderRoute: typeof Ikf360AdminAxesRouteImport
      parentRoute: typeof Ikf360AdminRoute
    }
    '/ikf360/admin/$id': {
      id: '/ikf360/admin/$id'
      path: '/$id'
      fullPath: '/ikf360/admin/$id'
      preLoaderRoute: typeof Ikf360AdminIdRouteImport
      parentRoute: typeof Ikf360AdminRoute
    }
    '/api/uploads/$id': {
      id: '/api/uploads/$id'
      path: '/api/uploads/$id'
      fullPath: '/api/uploads/$id'
      preLoaderRoute: typeof ApiUploadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/stage2-nudge': {
      id: '/api/cron/stage2-nudge'
      path: '/api/cron/stage2-nudge'
      fullPath: '/api/cron/stage2-nudge'
      preLoaderRoute: typeof ApiCronStage2NudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/review-reminders': {
      id: '/api/cron/review-reminders'
      path: '/api/cron/review-reminders'
      fullPath: '/api/cron/review-reminders'
      preLoaderRoute: typeof ApiCronReviewRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/monthly-content': {
      id: '/api/cron/monthly-content'
      path: '/api/cron/monthly-content'
      fullPath: '/api/cron/monthly-content'
      preLoaderRoute: typeof ApiCronMonthlyContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ikf360/admin/profiles/$id': {
      id: '/ikf360/admin/profiles/$id'
      path: '/profiles/$id'
      fullPath: '/ikf360/admin/profiles/$id'
      preLoaderRoute: typeof Ikf360AdminProfilesIdRouteImport
      parentRoute: typeof Ikf360AdminRoute
    }
  }
}

interface Ikf360AdminRouteChildren {
  Ikf360AdminIdRoute: typeof Ikf360AdminIdRoute
  Ikf360AdminAxesRoute: typeof Ikf360AdminAxesRoute
  Ikf360AdminCellsRoute: typeof Ikf360AdminCellsRoute
  Ikf360AdminContentRoute: typeof Ikf360AdminContentRoute
  Ikf360AdminProvidersRoute: typeof Ikf360AdminProvidersRoute
  Ikf360AdminTemplatesRoute: typeof Ikf360AdminTemplatesRoute
  Ikf360AdminProfilesIdRoute: typeof Ikf360AdminProfilesIdRoute
}

const Ikf360AdminRouteChildren: Ikf360AdminRouteChildren = {
  Ikf360AdminIdRoute: Ikf360AdminIdRoute,
  Ikf360AdminAxesRoute: Ikf360AdminAxesRoute,
  Ikf360AdminCellsRoute: Ikf360AdminCellsRoute,
  Ikf360AdminContentRoute: Ikf360AdminContentRoute,
  Ikf360AdminProvidersRoute: Ikf360AdminProvidersRoute,
  Ikf360AdminTemplatesRoute: Ikf360AdminTemplatesRoute,
  Ikf360AdminProfilesIdRoute: Ikf360AdminProfilesIdRoute,
}

const Ikf360AdminRouteWithChildren = Ikf360AdminRoute._addFileChildren(
  Ikf360AdminRouteChildren,
)

interface Ikf360RouteChildren {
  Ikf360AdminRoute: typeof Ikf360AdminRouteWithChildren
  Ikf360DashboardRoute: typeof Ikf360DashboardRoute
  Ikf360IntentRoute: typeof Ikf360IntentRoute
  Ikf360PreReviewRoute: typeof Ikf360PreReviewRoute
  Ikf360SupportRoute: typeof Ikf360SupportRoute
  Ikf360UploadRoute: typeof Ikf360UploadRoute
  Ikf360IndexRoute: typeof Ikf360IndexRoute
}

const Ikf360RouteChildren: Ikf360RouteChildren = {
  Ikf360AdminRoute: Ikf360AdminRouteWithChildren,
  Ikf360DashboardRoute: Ikf360DashboardRoute,
  Ikf360IntentRoute: Ikf360IntentRoute,
  Ikf360PreReviewRoute: Ikf360PreReviewRoute,
  Ikf360SupportRoute: Ikf360SupportRoute,
  Ikf360UploadRoute: Ikf360UploadRoute,
  Ikf360IndexRoute: Ikf360IndexRoute,
}

const Ikf360RouteWithChildren =
  Ikf360Route._addFileChildren(Ikf360RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoachesRoute: CoachesRoute,
  CodepenExportRoute: CodepenExportRoute,
  DonateRoute: DonateRoute,
  Ikf360Route: Ikf360RouteWithChildren,
  InitiativesRoute: InitiativesRoute,
  LoginRoute: LoginRoute,
  ParentsRoute: ParentsRoute,
  PartnersRoute: PartnersRoute,
  PlayersRoute: PlayersRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  ParentsPathwayRoute: ParentsPathwayRoute,
  ApiCronMonthlyContentRoute: ApiCronMonthlyContentRoute,
  ApiCronReviewRemindersRoute: ApiCronReviewRemindersRoute,
  ApiCronStage2NudgeRoute: ApiCronStage2NudgeRoute,
  ApiUploadsIdRoute: ApiUploadsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
